// Declarative architecture diagrams, rendered by components/Diagram.tsx.
// Coordinates are in a 960-wide viewBox. `notes` is what the reader sees when
// they hover or tap a node — write them as "what it does and why it exists".

export type NodeKind = "agent" | "service" | "store" | "external" | "guard" | "human" | "ui" | "tool";

export type DNode = { id: string; label: string; sub?: string; x: number; y: number; w?: number; h?: number; kind: NodeKind };
export type DEdge = { from: string; to: string; label?: string; dashed?: boolean };
export type DiagramSpec = { w: number; h: number; nodes: DNode[]; edges: DEdge[]; notes: Record<string, string> };

export const diagrams: Record<string, DiagramSpec> = {
  "delivery-fleet": {
    w: 960,
    h: 400,
    nodes: [
      { id: "autostart", label: "Auto-starter", sub: "08:00–21:00 IST|Sundays gated off", x: 20, y: 20, w: 160, kind: "service" },
      { id: "registry", label: "Session registry", sub: "rolls back on start failure", x: 210, y: 20, w: 160, kind: "service" },
      { id: "session", label: "TripSession ×20", sub: "Claude Agent SDK|one per rider, per day", x: 400, y: 20, w: 180, kind: "agent" },
      { id: "subagents", label: "5 subagents", sub: "empath · profile · ritual|hiring_context · skill_author", x: 610, y: 20, w: 170, kind: "agent" },
      { id: "dashboard", label: "Operator dashboard", sub: "live trace stream|isolated chat session", x: 800, y: 20, w: 150, kind: "ui" },
      { id: "replica", label: "Postgres read replica", sub: "trips · logs · telemetry", x: 130, y: 160, w: 170, kind: "store" },
      { id: "mcp", label: "In-process MCP", sub: "12 tools: snapshot, log delta,|tickets, WhatsApp, vision, SQL", x: 400, y: 160, w: 190, kind: "tool" },
      { id: "rules", label: "Rule-based nudges", sub: "zero-LLM templates|+ freshness guard at send time", x: 620, y: 160, w: 180, kind: "service" },
      { id: "freshdesk", label: "Freshdesk", sub: "tickets, 3-tier dedup", x: 830, y: 160, w: 120, kind: "external" },
      { id: "watchdog", label: "Watchdog + healthcheck", sub: "alarms when the agents go quiet", x: 130, y: 300, w: 190, kind: "guard" },
      { id: "inbox", label: "DriverInbox", sub: "recipient · respect · figure guards|debounce, one choke point", x: 400, y: 300, w: 190, kind: "guard" },
      { id: "waha", label: "WhatsApp (WAHA)", sub: "self-hosted, EC2", x: 640, y: 300, w: 150, kind: "external" },
      { id: "rider", label: "Rider", x: 840, y: 300, w: 100, kind: "human" },
    ],
    edges: [
      { from: "autostart", to: "registry" },
      { from: "registry", to: "session" },
      { from: "session", to: "subagents" },
      { from: "session", to: "dashboard", label: "trace" },
      { from: "session", to: "mcp", label: "tool calls" },
      { from: "mcp", to: "replica", label: "reads" },
      { from: "mcp", to: "freshdesk", label: "1 write" },
      { from: "session", to: "rules", label: "sweeps" },
      { from: "mcp", to: "inbox", label: "whatsapp_comm" },
      { from: "rules", to: "inbox", label: "templates" },
      { from: "inbox", to: "waha" },
      { from: "waha", to: "rider" },
      { from: "rider", to: "session", label: "replies", dashed: true },
      { from: "watchdog", to: "session", dashed: true },
    ],
    notes: {
      autostart: "Spawns one session per active rider inside the shift window and refills after deploys. Sundays are gated off at every spawn path, not just one — the fleet should be structurally quiet when the riders are.",
      registry: "Holds the live sessions. After an outage where dead sessions stayed registered as 'running' (and the dashboard showed more agents than riders), a failed start now rolls back, pinned by a test: N failed spawns ⇒ 0 agents live.",
      session: "A long-lived Claude Agent SDK session that watches one rider's whole day: pulls log deltas, decides whether each event is an anomaly, coaches in Hinglish, escalates only when something is genuinely wrong. The same agent handles first-mile and last-mile trips — one primer paragraph and a mode-aware snapshot, no fork.",
      subagents: "Specialists the orchestrator delegates to: an empath that drafts every rider-facing message, a driver-profile reader, a strict-vs-soft adjudicator, a morning/EOD ritual, and a skill author that distils learnings at the end of the day (and refuses observations the rider could just be asked about).",
      dashboard: "Operators see the full agent trace streamed live. The operator's chat with a trip runs as a second, isolated SDK session that shares the tools but never the strategist's memory — a /btw conversation that can't poke the autonomous flow.",
      replica: "Every read goes through asyncpg on the read replica, scoped to today in IST. The one write in the whole system — a ticket insert — goes through a separate primary pool.",
      mcp: "The agent's hands: trip snapshot, log delta (cumulative logs walked and deduped), telemetry, ticket search, ticket creation, WhatsApp, push, vision over photos, and a read-only SQL passthrough with a statement timeout and a hard row cap.",
      rules: "The ~60% cost lever. Heartbeats, chases, pickup reminders and greetings turned out to be templates — '{name}, {facts} — {action}?' — so they became deterministic Python over the already-fetched snapshot. Escalations, inbound replies and judgement calls stay with the LLM.",
      freshdesk: "Tickets are filed through the platform's own pipeline, with three-tier dedup (in-process ledger, a 7-day replica check, and a tool the agent calls to inspect real tickets before escalating).",
      watchdog: "Alarms when the agents stop — not just when inbound stops — because a silent fleet looks exactly like a calm one. The container fails its healthcheck if it can't run agents at all.",
      inbox: "The single path every agent-authored message must pass. Recipient guard: block only on a proven mismatch, allow every uncertainty. Respect guard: riders are always 'aap'. Figure guard: no invented numbers. Debounce and rate limits live here too.",
      waha: "Self-hosted WhatsApp gateway. Rider replies come back through a webhook, buffered per chat and fanned out to the agent.",
      rider: "A real person with a real day. The CEO's brief was explicit: a supportive partner, not a robotic alerting system.",
    },
  },

  "buyer-mcp": {
    w: 960,
    h: 360,
    nodes: [
      { id: "clients", label: "Claude clients", sub: "Desktop · Claude Code|WhatsApp sales agent", x: 20, y: 20, w: 190, kind: "ui" },
      { id: "oauth", label: "OAuth 2.0 (DCR + PKCE)", sub: "the authorize step IS phone + OTP", x: 270, y: 20, w: 220, kind: "guard" },
      { id: "jwt", label: "Per-buyer JWT", sub: "180-day refresh|row-scoped everywhere", x: 540, y: 20, w: 170, kind: "guard" },
      { id: "mcp", label: "Buyer MCP server", sub: "100 typed tools · streamable HTTP", x: 270, y: 160, w: 220, kind: "service" },
      { id: "parity", label: "The app's own pure functions", sub: "cart · coupon · deeplink maths,|imported verbatim", x: 540, y: 160, w: 210, kind: "tool" },
      { id: "honest", label: "Honest-absence outputs", sub: "reports WHY a SKU has no coupon", x: 780, y: 160, w: 170, kind: "guard" },
      { id: "hasura", label: "Hasura GraphQL", sub: "buyer role · 'nothing more,|nothing less'", x: 160, y: 290, w: 170, kind: "store" },
      { id: "rest", label: "REST backend", sub: "support · payouts · media", x: 380, y: 290, w: 160, kind: "store" },
      { id: "money", label: "Money-gated tools", sub: "place_order · redeem · payout", x: 600, y: 290, w: 190, kind: "guard" },
    ],
    edges: [
      { from: "clients", to: "oauth" },
      { from: "oauth", to: "jwt" },
      { from: "jwt", to: "mcp", label: "bearer" },
      { from: "mcp", to: "hasura" },
      { from: "mcp", to: "rest" },
      { from: "mcp", to: "parity", label: "imports" },
      { from: "parity", to: "honest" },
      { from: "mcp", to: "money", label: "blocked for the sales agent", dashed: true },
    ],
    notes: {
      clients: "Consumed three ways: Claude Desktop and Connectors (via OAuth), Claude Code (via a key), and programmatically by the WhatsApp sales agent, which mints a buyer JWT server-side per conversation.",
      oauth: "Dynamic client registration plus PKCE, where the authorization screen is the buyer's real login — phone number, OTP. The access token the client receives is the buyer's own app JWT. No shadow identity.",
      jwt: "Every tool runs as exactly one authenticated buyer. The platform's buyer role enforces the boundary at the data layer, so the MCP can't accidentally widen it.",
      mcp: "Grew from 87 to 100 tools over the summer: catalogue, sellers, cart, coupons, orders, support tickets, addresses, payouts, wallet, referrals, folds (the app's home-screen layout), media upload. A full sweep of the read tools returned zero genuine failures.",
      parity: "Discount maths is imported from the app, not re-implemented — so the agent and the app can never disagree on a price. When app GraphQL operations drifted from live Hasura, thin local overrides were added rather than forking them.",
      honest: "Upstream coupon gates fail open and are non-deterministic. A tool that returned an empty list would force the agent to say 'no offers' — so coupon lookups return the SKUs without coupons and a caveat explaining why, and the agent is forbidden from claiming absence.",
      hasura: "The same GraphQL the app calls, replayed with the buyer's token and the buyer role's headers. Row scoping is the platform's, which is the point.",
      rest: "Dynamic support forms, payouts, presigned uploads — the parts of the app that aren't GraphQL.",
      money: "Tools that move money or place orders exist in the MCP but are blocked for the WhatsApp sales agent. That single block is what makes 'your order has been placed' a claim the agent can never truthfully make — and therefore one it can never make.",
    },
  },

  "whatsapp-sales-agent": {
    w: 960,
    h: 400,
    nodes: [
      { id: "buyer", label: "Retailer on WhatsApp", x: 20, y: 20, w: 180, kind: "human" },
      { id: "aisensy", label: "AiSensy webhook", sub: "posts direct · acked in ~1 ms", x: 250, y: 20, w: 180, kind: "external" },
      { id: "ingest", label: "Ingest + dedup", sub: "background task with a held ref", x: 480, y: 20, w: 180, kind: "service" },
      { id: "spam", label: "Spam classifier", sub: "Haiku", x: 710, y: 20, w: 140, kind: "tool" },
      { id: "bmcp", label: "Buyer MCP", sub: "100 tools, per-buyer JWT", x: 20, y: 160, w: 180, kind: "service" },
      { id: "worker", label: "Worker agent", sub: "tool-using · Haiku/Sonnet tiered|its text is only a draft", x: 250, y: 160, w: 200, kind: "agent" },
      { id: "facts", label: "FACTS bundle", sub: "payable · cart link · ticket,|captured from tool results", x: 500, y: 160, w: 190, kind: "guard" },
      { id: "reply", label: "Reply agent", sub: "tool-less · the only voice", x: 740, y: 160, w: 170, kind: "agent" },
      { id: "gates", label: "PreToolUse gates", sub: "no callback-only tickets · look first|no duplicate in 12 h", x: 250, y: 300, w: 240, kind: "guard" },
      { id: "send", label: "Guarded send", sub: "cart link + price reinserted|split into bubbles", x: 540, y: 300, w: 180, kind: "guard" },
      { id: "analytics", label: "Attribution sweeps", sub: "reconciled to the replica", x: 760, y: 300, w: 170, kind: "store" },
    ],
    edges: [
      { from: "buyer", to: "aisensy" },
      { from: "aisensy", to: "ingest" },
      { from: "ingest", to: "spam" },
      { from: "ingest", to: "worker" },
      { from: "worker", to: "bmcp", label: "tool calls" },
      { from: "worker", to: "gates", dashed: true },
      { from: "worker", to: "facts" },
      { from: "facts", to: "reply" },
      { from: "reply", to: "send" },
      { from: "send", to: "buyer", label: "reply", dashed: true },
      { from: "send", to: "analytics", label: "traces" },
    ],
    notes: {
      buyer: "A neighbourhood retail-store owner who messaged the brand's WhatsApp number. They want a price, an offer, or to know where their order is — in Hinglish, now.",
      aisensy: "The WhatsApp provider posts straight to the service. It used to go through an automation tool whose 15,000-deep FIFO queue delayed replies by hours and then stopped delivering entirely. The webhook acknowledges in about a millisecond and does the work in the background.",
      ingest: "Dedup runs at ingest, not later, which closed a race during the cutover. Background tasks hold a strong reference — six sweeps had previously died after one run because nothing held them and the garbage collector took them mid-sleep.",
      spam: "A cheap classifier in front of the expensive agent. Buyers who are only passing time get three attempts at a sale and are then opted out with zero further LLM spend; an operator can resume them from the dashboard.",
      bmcp: "The same Buyer MCP that Claude Desktop uses, with money-moving tools blocked for this consumer.",
      worker: "Does the reasoning with tools. Its own text used to be the leak source — 'waiting for results', 'my tools are connecting' — so it no longer writes what the buyer sees.",
      facts: "Money and links are never taken from the model's prose. The payable amount, the cart deeplink and any ticket number are captured from tool results and handed to the reply agent as facts.",
      reply: "A tool-less agent rewrites the draft from the facts. Structurally it cannot emit tool narration. It enforces 'aap', gender-aware address, and silence when a chat is genuinely concluded.",
      gates: "Deterministic hooks that fire even when permissions are bypassed. A ticket can't be filed for 'call me back' alone, can't be filed without first reading existing tickets, and can't duplicate one raised in the last 12 hours.",
      send: "A final deterministic pass reinserts the cart link and price if the reply dropped them, then splits the message into WhatsApp-sized bubbles.",
      analytics: "Every tile on the mission-control dashboard reconciles exactly against the production replica, and the headline tile is keyed on exact cart-ID match — the only causal attribution the system can defend.",
    },
  },

  "order-lifecycle-automation": {
    w: 960,
    h: 370,
    nodes: [
      { id: "replica", label: "Orders + shipments", sub: "Postgres read replica", x: 20, y: 20, w: 190, kind: "store" },
      { id: "ticks", label: "4 pollers", sub: "main · courier · cancel · partial", x: 270, y: 20, w: 190, kind: "service" },
      { id: "event", label: "Event-time guard", sub: "marked*Time or created_at —|never updated_at", x: 520, y: 20, w: 200, kind: "guard" },
      { id: "cluster", label: "Bulk-cluster guard", sub: "any same-timestamp cluster|> 50 rows is dropped whole", x: 760, y: 20, w: 190, kind: "guard" },
      { id: "admin", label: "Admin dashboard", sub: "stop switch · every send, audited", x: 20, y: 160, w: 190, kind: "ui" },
      { id: "d2r", label: "D2R-only gate", sub: "join on the seller flag,|never on the name", x: 270, y: 160, w: 190, kind: "guard" },
      { id: "stage", label: "Stage mapper", sub: "10 stages · vocabulary checked|against the DB at boot", x: 520, y: 160, w: 200, kind: "service" },
      { id: "ledger", label: "Send ledger", sub: "Supabase · one row per order+stage", x: 760, y: 160, w: 190, kind: "store" },
      { id: "aisensy", label: "AiSensy templates", sub: "Meta-approved utility messages", x: 520, y: 300, w: 200, kind: "external" },
      { id: "buyer", label: "Buyer", x: 800, y: 300, w: 110, kind: "human" },
    ],
    edges: [
      { from: "replica", to: "ticks" },
      { from: "ticks", to: "event", label: "main" },
      { from: "ticks", to: "cluster", label: "courier", dashed: true },
      { from: "event", to: "d2r" },
      { from: "cluster", to: "d2r" },
      { from: "d2r", to: "stage" },
      { from: "stage", to: "ledger" },
      { from: "ledger", to: "aisensy" },
      { from: "aisensy", to: "buyer" },
      { from: "admin", to: "ticks", dashed: true },
    ],
    notes: {
      replica: "Order and courier-shipment tables on the read replica. The only indexed change signal is updated_at, which is fine to scan on and fatal to trigger on.",
      ticks: "Four independent pollers, each owning the stages it can observe: order confirmation and delivery from orders, in-flight stages from courier shipments, cancellations, and partial deliveries. A latent cursor pin (poll_max_orders at 94% of a real cluster) was found and fixed before it bit.",
      event: "Born from the incident. A staged message sends only if its own event timestamp — markedDeliveredTime, created_at — is recent. Replaying the incident window with the clock frozen: 2,140 stale rows blocked, 64 genuine ones passed.",
      cluster: "For the courier tick, which has no per-status event column. The bulk job's own signature is the tell: any cluster of identical timestamps larger than 50 rows is dropped whole. The largest natural cluster measured was 9; the bulk waves were 2,600–15,000. It fired on a real 276-row recon touch within minutes of deploy.",
      admin: "A stop switch, a live state header, and every send with its template, status and timestamp. Incident rows are kept — they're history.",
      d2r: "Other order flows share these tables. Every fetcher joins on the seller's D2R flag; one brand had seven seller rows with only one live, so a name filter would have silenced a top seller. Verified zero non-D2R sellers across five fetchers before deploy.",
      stage: "Maps raw statuses to the ten message stages. At boot it checks the stage vocabulary against the database constraint and logs loudly on mismatch — because a silently rejected stage once hid for hours behind a per-order log line.",
      ledger: "Idempotency: one row per order and stage. Refund promises are gated on the real refundable-amount column, never inferred from status.",
      aisensy: "Templated utility messages in Hindi with app deeplinks. Three of twelve templates were once silently dead in production; the boot-time check is why that can't recur unnoticed.",
      buyer: "Gets confirmed, dispatched, out-for-delivery, delivered, RTO, cancelled and partial-delivery messages — about 500 a day, and only about their own current orders.",
    },
  },

  "delhivery-ops-autopilot": {
    w: 960,
    h: 380,
    nodes: [
      { id: "vendor", label: "Delhivery ops API", sub: "Keycloak-backed vendor session", x: 20, y: 20, w: 200, kind: "external" },
      { id: "client", label: "API client", sub: "fails fast when the session is dead", x: 270, y: 20, w: 190, kind: "service" },
      { id: "token", label: "TokenManager.live()", sub: "exp in the future AND|no _dead latch", x: 510, y: 20, w: 200, kind: "guard" },
      { id: "slack", label: "Slack one-shot alarm", sub: "live → dead, then silence", x: 760, y: 20, w: 190, kind: "external" },
      { id: "loops", label: "8 background loops", sub: "recon · triage · AI triage|keepalive · snapshot guard…", x: 270, y: 160, w: 210, kind: "service" },
      { id: "judge", label: "Claude judge", sub: "per-stream flags · Semaphore(5)|Haiku 4.5 by default", x: 530, y: 160, w: 190, kind: "agent" },
      { id: "vision", label: "Vision on exception images", sub: "the vendor's own weight photos", x: 760, y: 160, w: 190, kind: "tool" },
      { id: "queue", label: "Action Center", sub: "approve · raise selected|live-checks before filing", x: 270, y: 300, w: 210, kind: "ui" },
      { id: "writes", label: "Paced auto-filing", sub: "throttle · 429/503 backoff|write ledger + deeplink", x: 530, y: 300, w: 210, kind: "guard" },
      { id: "mcp", label: "Remote MCP · 30 tools", sub: "bearer-gated, any Claude client", x: 780, y: 300, w: 170, kind: "service" },
    ],
    edges: [
      { from: "loops", to: "client" },
      { from: "client", to: "vendor" },
      { from: "vendor", to: "token", label: "invalid_grant trips the latch", dashed: true },
      { from: "token", to: "loops", label: "gates" },
      { from: "token", to: "judge", label: "gates" },
      { from: "token", to: "slack" },
      { from: "loops", to: "judge" },
      { from: "judge", to: "vision" },
      { from: "judge", to: "queue" },
      { from: "queue", to: "writes" },
      { from: "writes", to: "client" },
      { from: "mcp", to: "client" },
    ],
    notes: {
      vendor: "Our courier partner's operations API — claims, tickets, shipment status, weight-exception images — behind a vendor session that can be revoked at any time.",
      client: "Every read and write goes through one client. When the session is dead, every call short-circuits with zero network traffic instead of one 400 per call — added after a single MCP client produced an 11-call burst in 12 seconds against a dead session.",
      token: "The single kill switch for money. A revoked refresh token can still look unexpired by its own clock, so expiry alone is untrusted: a latch trips the moment the auth server answers invalid_grant, and clears when a fresh token is pasted — no redeploy. It fails open on a non-JWT token so a healthy session is never falsely paused.",
      slack: "One alarm on the live→dead transition, then quiet. The daily report is gated off while dead — no nagging, and Slack never bills.",
      loops: "Reconciliation, deterministic triage, AI triage, EDT sync, keepalive, snapshot guard and more — all gated on one predicate. Before the fix, 'ready' meant a token file merely existed; the loops were hammering the vendor's auth server every 2.8 minutes with a months-dead session.",
      judge: "Claude decides what's critical per stream with a forced tool call and no hardcoded thresholds — v1's deterministic queue had produced '0 days past promised — expedite'. Two tuning bugs worth remembering: ~19 concurrent calls rate-limited the weight stream to empty (fixed with a shared semaphore), and a 'be thorough' prompt exceeded max_tokens and silently truncated (fixed with batching).",
      vision: "Weight claims are judged with the vendor's own sorter photos in front of the model, so 'this parcel is lighter than billed' is an observation, not a guess.",
      queue: "Humans approve; the system raises. Before filing it re-queries the vendor for each shipment and skips anything that already has an open ticket or claim, so stale flags never double-file.",
      writes: "Bulk writes are throttled with backoff so they never hammer the vendor. Every real submission is recorded in a write ledger and surfaced with a deeplink to the vendor's record.",
      mcp: "The same capability exposed as a remote MCP server, so any Claude client can ask 'which shipments are stuck?' — guarded by the same liveness gate.",
    },
  },

  "live-money-paths": {
    w: 960,
    h: 340,
    nodes: [
      { id: "app", label: "Buyer app", sub: "injects the logged-in|buyer's token into the URL", x: 20, y: 20, w: 200, kind: "ui" },
      { id: "webview", label: "Next.js webviews", sub: "refer-and-earn · scratch card", x: 270, y: 20, w: 200, kind: "service" },
      { id: "hasura", label: "Hasura, as that buyer", sub: "a forged token dies here;|we hold no signing secret", x: 520, y: 20, w: 200, kind: "guard" },
      { id: "ga4", label: "GA4 funnel", sub: "four steps, not one", x: 770, y: 20, w: 170, kind: "store" },
      { id: "replica", label: "Orders (read replica)", sub: "first DELIVERED order", x: 20, y: 160, w: 200, kind: "store" },
      { id: "poller", label: "Credit poller (180 s)", sub: "pays only on delivery,|never on signup alone", x: 270, y: 160, w: 200, kind: "service" },
      { id: "wallet", label: "Wallet ledger (primary DB)", sub: "partial unique index arbitrates|insert-first, no check-then-write", x: 520, y: 160, w: 220, kind: "guard" },
      { id: "aisensy", label: "AiSensy WhatsApp", sub: "status updates with deeplinks", x: 780, y: 160, w: 170, kind: "external" },
      { id: "qr", label: "One constant QR on every carton", sub: "no order · no buyer · no secret", x: 270, y: 280, w: 240, kind: "external" },
    ],
    edges: [
      { from: "qr", to: "app", label: "scan" },
      { from: "app", to: "webview" },
      { from: "webview", to: "hasura", label: "token" },
      { from: "hasura", to: "wallet", label: "claim" },
      { from: "webview", to: "ga4" },
      { from: "poller", to: "replica" },
      { from: "poller", to: "wallet", label: "credit" },
      { from: "wallet", to: "aisensy", label: "notify" },
    ],
    notes: {
      app: "One link serves every buyer: the app substitutes the logged-in user's token on open. Identity comes from the app, never from anything the buyer can type.",
      webview: "Two small Next.js apps on Vercel, designed for a 375-px phone inside the app's webview. Copy is Latin-script Hinglish only.",
      hasura: "The token is proven upstream by calling the platform as that buyer. A forged or expired token is rejected there and never reaches the credit path — and the service holds no secret that could leak.",
      ga4: "Scan → peek → reveal → claim, so a drop-off is visible at the step it happens.",
      replica: "The poller finds the referred buyer's first delivered order on the replica. Signup alone never pays the referrer — an activation metric, not a signup metric.",
      poller: "Reads pending referrals, checks for a first delivered order, credits via the platform, flips the row. It also backfills the referred buyer's bonus if the signup credit ever failed.",
      wallet: "The entire double-credit guarantee is one partial unique index on the wallet ledger. The claim writes first and lets Postgres arbitrate; a second insert is physically unstorable. Holds under double-tap, two devices, a retried serverless call, a redeploy mid-flight, replica lag, and a different buyer entirely. The wallet table is the claim ledger — no second source of truth on a money path.",
      aisensy: "Five utility-approved templates with app deeplinks, so a buyer learns about a credit from WhatsApp rather than by checking a wallet.",
      qr: "The QR is not a bearer token. If buyer B scans buyer A's carton, the page opens as B, looks up B's own delivered orders and pays B only what B is owed. The theft case isn't defended against — it's designed out.",
    },
  },

  "aditya-mcp": {
    w: 960,
    h: 300,
    nodes: [
      { id: "roots", label: "scan_roots", sub: "the only configuration", x: 20, y: 20, w: 170, kind: "store" },
      { id: "discover", label: "Discovery", sub: "git repos · *HANDOFF*.md · sessions,|re-walked on every call", x: 240, y: 20, w: 240, kind: "service" },
      { id: "sessions", label: "Claude Code session logs", sub: "matched by recorded cwd", x: 530, y: 20, w: 210, kind: "store" },
      { id: "git", label: "git log", sub: "read-only", x: 790, y: 20, w: 150, kind: "store" },
      { id: "tools", label: "7 read-only tools", sub: "sessions · commits · handoff entries|freshness · dashboard links · report", x: 240, y: 170, w: 260, kind: "service" },
      { id: "report", label: "Daily work report", sub: "scheduled routine", x: 560, y: 170, w: 170, kind: "agent" },
      { id: "nudge", label: "Stale-handoff nudger", sub: "messages the owning session", x: 770, y: 170, w: 170, kind: "agent" },
    ],
    edges: [
      { from: "roots", to: "discover" },
      { from: "discover", to: "sessions" },
      { from: "discover", to: "git" },
      { from: "discover", to: "tools" },
      { from: "tools", to: "report" },
      { from: "tools", to: "nudge" },
    ],
    notes: {
      roots: "Two folders. Everything else — repos, handoff docs, sessions — is discovered by walking them on every call, so a new project is covered the moment its folder exists.",
      discover: "Finds every git repo and every handoff doc under the roots, and every Claude Code session whose recorded working directory falls under them. Same-named docs in different worktrees are labelled by relative path so they don't collide.",
      sessions: "The raw session logs. The server peeks each candidate's cwd rather than trusting folder names, which is how sessions started from brand-new folders are caught.",
      git: "Commit history per discovered repo. It can't see uncommitted work — which in worktrees can be thousands of lines — so consumers are told to also check the working tree.",
      tools: "Everything is read-only, local, and makes no network calls. The server's own handoff documents a known omission in one date-range query rather than hiding it, and instructs consumers to reconcile against a second source.",
      report: "A scheduled routine that writes 'what did I work on yesterday' across every project, with commit counts, sessions and handoff entries.",
      nudge: "A companion routine that finds handoff docs older than their project's last activity and messages the responsible session to update them. Agents auditing agents.",
    },
  },
};
