// The resume, verbatim. Source of truth: ../applications/resume_copy.py
// (rendered by build_resume_v2.py variant `best` into public/Aditya_Mukhopadhyay_Resume.pdf,
// and by build_resume_ats.py into the single-column ATS file used for applications).
// GENERATED by ../applications/export_site_resume.py — edit resume_copy.py, not this file.
// Every project is three points: problem, solution, impact. **bold** marks emphasis.
// "INR" is deliberate: the PDF fonts cannot carry the rupee glyph.

export type ResumeLeaf = { kind: "sub" | "leaf" | "flat"; text: string };
export type ResumeRole = { title: string; date: string; items: ResumeLeaf[] };

export const resume = {
  name: { first: "Aditya", last: "Mukhopadhyay" },
  subtitle: "AI Engineer — Badho Technologies",
  contact: {
    email: "adul.m.2003@gmail.com",
    phone: "+91-9981861975",
    portfolio: { label: "Portfolio", href: "https://adityamukhopadhyay.vercel.app" },
    linkedin: { label: "LinkedIn", href: "https://www.linkedin.com/in/adityamukhopadhyay2003/" },
    github: { label: "GitHub", href: "https://github.com/adityamukhopadhyay/" },
  },
  pdfHref: "/Aditya_Mukhopadhyay_Resume.pdf",

  sidebar: {
    education: [
      { head: "B.Tech, Information Technology", body: "IGEC Sagar (RGPV), Madhya Pradesh", meta: "2021 – 2025 · CGPA 7.5" },
      { head: "Class XII (PCM)", body: "St. Joseph's Convent S.S. School, Ranjhi, Jabalpur", meta: "2021 · 93.4%" },
    ],
    links: [
      { head: "Portfolio", body: "adityamukhopadhyay.vercel.app", href: "https://adityamukhopadhyay.vercel.app" },
      { head: "LinkedIn", body: "linkedin.com/in/adityamukhopadhyay2003", href: "https://www.linkedin.com/in/adityamukhopadhyay2003/" },
      { head: "GitHub", body: "github.com/adityamukhopadhyay", href: "https://github.com/adityamukhopadhyay/" },
    ],
    skills: [
      { head: "Languages & Backend", body: "Python (pandas, NumPy, scikit-learn) · SQL · FastAPI · REST APIs · GraphQL (Hasura) · PostgreSQL · Supabase · Docker · AWS (Lambda, EC2, S3) · Git" },
      { head: "AI / ML", body: "Machine Learning · LLM agents · Claude Agent SDK · Model Context Protocol (MCP) · multi-agent orchestration · tool calling · RAG · vector search (FAISS) · embeddings · semantic search · clustering (HDBSCAN, K-Means) · prompt engineering · evaluation & guardrails · cost tracing · NLP · deep learning (CNNs) · Anthropic Claude, OpenAI GPT and Google Gemini APIs · n8n" },
      { head: "Leadership", body: "Managed a 3-person AI team · worked directly with stakeholders · client-facing delivery" },
    ],
    projects: [] as { head: string; meta: string; body: string }[],
  },

  summary:
    "AI Engineer who ships production large language model (LLM) agent systems end to end — multi-agent orchestration on the Claude Agent SDK, MCP tool servers, retrieval-augmented generation (RAG) and vector search, evaluation and guardrails, and classical ML — in Python, FastAPI and PostgreSQL on AWS.",

  roles: [
    {
      title: "AI Engineer | Badho Technologies Pvt. Ltd.",
      date: "Jun 2025 – Present",
      items: [
        { kind: "sub", text: "Autonomous Delivery Fleet — multi-agent orchestration (Claude Agent SDK, MCP, Python, PostgreSQL)" },
        { kind: "leaf", text: "Delivery failures surfaced only when a human noticed a stuck rider." },
        { kind: "leaf", text: "Architected a **per-rider orchestrator agent (~20 concurrent)** that delegates to messaging, escalation, judgement and route-planning sub-agents over one in-process MCP server, with **deterministic guards below the model**." },
        { kind: "leaf", text: "Runs **unattended 13-hour shifts** in production, backed by **23 offline test suites** and an \"Ask the fleet\" agent for operators." },
        { kind: "sub", text: "WhatsApp AI Sales Agent on Buyer MCP — conversational agent + the buyer app as 100 typed tools (Claude Agent SDK, MCP, Python, Hasura GraphQL, OAuth/JWT)" },
        { kind: "leaf", text: "Retailers asked questions and abandoned carts faster than a sales team could respond, and agents had no safe, permissioned way to act inside the buyer app." },
        { kind: "leaf", text: "Built an MCP server exposing search, carts, coupons, orders, wallet and tickets as **100 typed tools** behind phone-OTP OAuth and **per-buyer JWTs**, and on it a two-model agent: a tool-using worker plus a **tool-less reply agent with a claim verifier**, per-buyer queues and a bounded concurrency gate." },
        { kind: "leaf", text: "Handles buyer conversations end to end in production and influenced **475 orders (INR 5.0 lakh)**; the same MCP powers Claude Desktop and Claude Code, with the tool schema as the permission boundary." },
        { kind: "sub", text: "Courier Ops Autopilot — claims & ticket automation (FastAPI, remote MCP, Claude Haiku, vision)" },
        { kind: "leaf", text: "Money went unclaimed because weight-overcharge and failed-delivery filing with the courier was manual." },
        { kind: "leaf", text: "Created a backend, dashboard and bearer-gated remote MCP over the courier API that **auto-files weight claims from sorter images**, raises NDR / lost / damaged tickets and drafts vendor replies, behind a **single liveness gate**." },
        { kind: "leaf", text: "Filed **698 claims and 370 tickets in the first 24 hours**; **2,143 closed** to date." },
        { kind: "sub", text: "Search, Matching & Catalog Intelligence — ML pipeline (FAISS, HDBSCAN, embeddings, PostgreSQL, n8n)" },
        { kind: "leaf", text: "Hinglish and phonetic searches missed, **85,000+ SKUs** had no variant grouping, and **170,000+ competitor SKUs** needed catalogue mapping." },
        { kind: "leaf", text: "**Led a 3-person team** to ship **sub-100 ms hybrid search** (FAISS + local embeddings + metaphone), sister-product clustering (MiniLM, HDBSCAN / K-Means, shadow-write staging with human approval) and a cost-tiered matching funnel (exact → trigram → batched LLM)." },
        { kind: "leaf", text: "Mapped **~40,000 product groups**, lifted sister-product conversion from **20% to 60%**, and matched **170,000+ SKUs**." }
      ],
    },
    {
      title: "AI Developer (Freelance) | Strix Digital",
      date: "Jul 2023 – May 2025",
      items: [
        { kind: "flat", text: "Delivered AI web apps (a **cold-email generator on Groq**), scrapers, automation tooling and an **iOS app** for a Houston client, client-facing from scoping to hand-off." }
      ],
    },
    {
      title: "Data Science Intern | Acmegrade (in collaboration with IIT Bombay)",
      date: "Apr 2022 – Jun 2022",
      items: [
        { kind: "flat", text: "Built ML models for **movie recommendation**, **sales forecasting** and **CNN sound classification**, with EDA and feature engineering on multi-modal datasets." }
      ],
    },
  ] as ResumeRole[],

  // Checks that were actually run on the canonical PDF before it was published.
  checklist: [
    { label: "Fits on one page", detail: "nothing spills to a second page" },
    { label: "Reads cleanly as plain text", detail: "applicant-tracking systems get every line" },
    { label: "All key figures present", detail: "100 tools, ~20 agents, 23 test suites, 698 + 370, 2,143, 85,000+, 170,000+, 20% → 60%, 475 orders" },
    { label: "Links work", detail: "email · Portfolio · LinkedIn · GitHub" },
  ],
};

const strip = (s: string) => s.replace(/\*\*/g, "");

// What an ATS parser sees: the same content, in the PDF's reading order
// (whole sidebar, then the main column), with no formatting.
export function resumeAsPlainText(): string {
  const r = resume;
  const out: string[] = [];
  out.push(`${r.name.first} ${r.name.last}`, r.subtitle, `${r.contact.email} | ${r.contact.phone} | Portfolio | LinkedIn | GitHub`, "");
  out.push("EDUCATION");
  for (const e of r.sidebar.education) out.push(e.head, e.body, e.meta);
  out.push("", "LINKS");
  for (const l of r.sidebar.links) out.push(l.head, l.body);
  out.push("", "SKILLS");
  for (const s of r.sidebar.skills) out.push(s.head, s.body);
  out.push("", "PROJECTS");
  for (const p of r.sidebar.projects) out.push(p.head, p.meta, strip(p.body));
  out.push("", "SUMMARY", r.summary, "", "WORK EXPERIENCE");
  for (const role of r.roles) {
    out.push(`${role.title}  ${role.date}`);
    for (const it of role.items) out.push((it.kind === "leaf" ? "  ○ " : "• ") + strip(it.text));
  }
  return out.join("\n");
}
